
markdown: kramdown
highligter: null
permalink: /:title

url:
baseurl: ""

redcarpet:
  extensions: [strikethrough, tables]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap	
sass:
  sass_dir: public/css
  style: :compressed

github_username:    tomoyatakano
googlescholar_username:	a0Boi-0AAAAJ
researchgate_username:	Tomoya_Takano
orcid_username: 0000-0002-0178-9707
email_username: ttakano@eri.u-tokyo.ac.jp

google_analytics: UA-129038024-1
